services:
  - type: web
    name: Job RAG Agent
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --prefer-binary -r requirements-prod.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker api.main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
